FROM bitnami/spark:latest

# Copy your Python dependencies
COPY requirements.txt .

# Switch to root to install packages
USER root

# Install pip and packages from requirements.txt
RUN apt-get clean && \
    apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --no-cache-dir -r ./requirements.txt
